export const FETCH_ADS_REQUEST_SENT = 'FETCH_ADS_REQUEST_SENT'
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS'
export const FETCH_ADS_FAIL = 'FETCH_ADS_FAIL'

export const CURRENT_LOCATION_REQUEST_SENT = 'CURRENT_LOCATION_REQUEST_SENT'
export const CURRENT_LOCATION_SUCCESS = 'CURRENT_LOCATION_SUCCESS'
export const CURRENT_LOCATION_FAIL = 'CURRENT_LOCATION_FAIL'

export const FETCH_FATA_REQUEST_SENT = 'FETCH_FATA_REQUEST_SENT'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'