export const messageTypes = {
  MESSAGE: 1,
  QUESTIONNAIRE: 2,
  OFFER: 3,
  OFFER_WITHDRAWN: 4,
  CHAT_REQUEST_ACCEPTED: 5,
  ANSWERS_SUBMITTED: 6,
  ANSWERS_CHNAGED: 7,
  CANT_FIND_INSURANCE_PRODUCT: 9
}

export const notificationTypes = {
  SYSTEM: 1,
  CHAT_REQUEST_SENT: 2,
  MESSAGE: 3,
  CHAT_REQUEST_ACCEPTED: 4,
  CHAT_REQUEST_REJECTED: 5,
  OFFER_SENT: 6,
  OFFER_ACCEPTED: 7,
  OFFER_REJECTED: 8,
  HIDE_REQUESTS: 9,
    SHOW_REQUEST: 10,
  CHAT_REQUEST_REMINDER: 11,
  NEW_REQUEST_CREATED: 12,
  ANSWERS_SUBMITTED: 13,
  ANSWERS_CHANGED: 15,
  QUESTIONNAIRE_CLARIFICATION: 14,
  OFFER_DECLINED: 16,
  CANT_FIND_INSURANCE_PRODUCT: 17
}

export const requestsByStatus = {
  NEW: 1,
  FAVOURITE: 2,
  REJECTED: 3,
  ACCEPTED: 4,
  NOT_RESPONDED: 5,
  SIGNED: 6,
  LOST: 7,
}

export const chatRequestStatus = {
  NOT_RESPONDED: 0,
  ACCEPTED: 1,
  REJECTED: 2,
  IN_ACTIVE: 3 // when first message is not sent.
}

export const PER_PAGE = 10